### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by leftTheBurnerOn** [gameworkers/fdafdfas#1]
- [ ] crunch/simplify svgs
- [ ] add other images
- [ ] if we want to use transparent isabelle image at large scale in intro, should probably use jpg+svg masking instead of png
- [ ] Union Faqs template
- [ ] Back/forward navigation reading from contents.js
- [ ] Table of components footer component
- [ ] Variant covers section below table of contents linking images to pdfs
- [ ] Header component with nintendo power logo and link back to gwu site
- [ ] Figure out hosting/url situation
